/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Win 10
 */
public class Panel_Ve extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Ve
     */
    public Panel_Ve() {
        initComponents();
        this.setBounds(0, 0, 672, 496);
        this.setBorder(BorderFactory.createLineBorder(Color.black));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblVe = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblTour = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        txtMave = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtThoigiandat = new javax.swing.JTextField();
        txtTrangthai = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtMatourve = new javax.swing.JTextField();
        txtTentourve = new javax.swing.JTextField();
        txtTenkhve = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtMakhve = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ VÉ");
        add(jLabel1);
        jLabel1.setBounds(227, 11, 197, 44);

        tblVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Vé", "Mã Tour", "Mã KH", "Thời Gian Đặt", "Trạng Thái", "Giá"
            }
        ));
        jScrollPane9.setViewportView(tblVe);

        add(jScrollPane9);
        jScrollPane9.setBounds(10, 61, 652, 153);

        tblTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tour", "Tên Tour"
            }
        ));
        jScrollPane10.setViewportView(tblTour);

        add(jScrollPane10);
        jScrollPane10.setBounds(10, 220, 177, 100);

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên KH"
            }
        ));
        jScrollPane11.setViewportView(tblKhachHang);

        add(jScrollPane11);
        jScrollPane11.setBounds(205, 220, 177, 100);

        jLabel31.setText("Mã Vé:");
        add(jLabel31);
        jLabel31.setBounds(422, 226, 33, 14);
        add(txtMave);
        txtMave.setBounds(512, 223, 150, 20);

        jLabel34.setText("Thời Gian Đặt:");
        add(jLabel34);
        jLabel34.setBounds(422, 264, 69, 14);
        add(txtThoigiandat);
        txtThoigiandat.setBounds(512, 261, 150, 20);
        add(txtTrangthai);
        txtTrangthai.setBounds(512, 303, 150, 20);

        jLabel35.setText("Trạng Thái:");
        add(jLabel35);
        jLabel35.setBounds(422, 306, 55, 14);

        jLabel36.setText("Giá:");
        add(jLabel36);
        jLabel36.setBounds(422, 341, 19, 14);
        add(txtGia);
        txtGia.setBounds(512, 341, 150, 20);

        jLabel27.setText("Mã Tour:");
        add(jLabel27);
        jLabel27.setBounds(10, 341, 43, 14);

        jLabel28.setText("Tên Tour:");
        add(jLabel28);
        jLabel28.setBounds(10, 379, 47, 14);
        add(txtMatourve);
        txtMatourve.setBounds(63, 338, 124, 20);

        txtTentourve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTentourveActionPerformed(evt);
            }
        });
        add(txtTentourve);
        txtTentourve.setBounds(63, 376, 124, 20);
        add(txtTenkhve);
        txtTenkhve.setBounds(253, 376, 129, 20);

        jLabel30.setText("Tên KH:");
        add(jLabel30);
        jLabel30.setBounds(205, 379, 38, 14);

        jLabel29.setText("Mã KH:");
        add(jLabel29);
        jLabel29.setBounds(205, 341, 34, 14);

        txtMakhve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMakhveActionPerformed(evt);
            }
        });
        add(txtMakhve);
        txtMakhve.setBounds(253, 338, 129, 20);

        btnThem.setText("Thêm");
        add(btnThem);
        btnThem.setBounds(101, 430, 77, 32);

        btnXoa.setText("Xóa");
        add(btnXoa);
        btnXoa.setBounds(196, 430, 77, 32);

        btnSua.setText("Sửa");
        add(btnSua);
        btnSua.setBounds(291, 430, 77, 32);

        btnTimKiem.setText("Tìm kiếm");
        add(btnTimKiem);
        btnTimKiem.setBounds(386, 430, 77, 32);

        btnLamMoi.setText("Làm mới");
        add(btnLamMoi);
        btnLamMoi.setBounds(481, 430, 77, 32);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTentourveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTentourveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTentourveActionPerformed

    private void txtMakhveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMakhveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMakhveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTable tblTour;
    private javax.swing.JTable tblVe;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMakhve;
    private javax.swing.JTextField txtMatourve;
    private javax.swing.JTextField txtMave;
    private javax.swing.JTextField txtTenkhve;
    private javax.swing.JTextField txtTentourve;
    private javax.swing.JTextField txtThoigiandat;
    private javax.swing.JTextField txtTrangthai;
    // End of variables declaration//GEN-END:variables
}
