/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.VeBLL;
import DAL.KhachHangDAL;
import DAL.TourDAL;
import DAL.VeDAL;
import DTO.KhachHangDTO;
import DTO.TourDTO;
import DTO.VeDTO;
import java.awt.Color;
import java.sql.Array;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Win 10
 */
public class Panel_Ve extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Ve
     */
    private List<KhachHangDTO> khachhang;
    private DefaultTableModel modelkh;

    private List<TourDTO> tour;
    private DefaultTableModel modeltour;

    private List<VeDTO> ve;
    private DefaultTableModel modelve;

    public Panel_Ve() {
        initComponents();
        this.setBounds(0, 0, 672, 496);
        this.setBorder(BorderFactory.createLineBorder(Color.black));

        txtTenkhve.setEditable(false);
        txtTentourve.setEditable(false);

        khachhang = new ArrayList<>();
        modelkh = (DefaultTableModel) tblKhachHang.getModel();
        showKhachHang();

        tour = new ArrayList<>();
        modeltour = (DefaultTableModel) tblTour.getModel();
//        showTour();

        ve = new ArrayList<>();
        modelve = (DefaultTableModel) tblVe.getModel();
        showVe();
        TimKiem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblVe = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblTour = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        txtMave = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtThoigiandat = new javax.swing.JTextField();
        txtTrangthai = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtTentourve = new javax.swing.JTextField();
        txtTenkhve = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ VÉ");
        add(jLabel1);
        jLabel1.setBounds(227, 11, 197, 44);

        tblVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Vé", "Mã Tour", "Mã KH", "Thời Gian Đặt", "Trạng Thái", "Giá"
            }
        ));
        jScrollPane9.setViewportView(tblVe);

        add(jScrollPane9);
        jScrollPane9.setBounds(10, 90, 652, 153);

        tblTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tour", "Tên Tour"
            }
        ));
        tblTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTourMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(tblTour);

        add(jScrollPane10);
        jScrollPane10.setBounds(10, 260, 177, 100);

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên KH"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tblKhachHang);

        add(jScrollPane11);
        jScrollPane11.setBounds(210, 260, 177, 100);

        jLabel31.setText("Mã Vé:");
        add(jLabel31);
        jLabel31.setBounds(420, 260, 33, 14);
        add(txtMave);
        txtMave.setBounds(510, 260, 150, 20);

        jLabel34.setText("Thời Gian Đặt:");
        add(jLabel34);
        jLabel34.setBounds(420, 300, 69, 14);
        add(txtThoigiandat);
        txtThoigiandat.setBounds(510, 300, 150, 20);
        add(txtTrangthai);
        txtTrangthai.setBounds(510, 340, 150, 20);

        jLabel35.setText("Trạng Thái:");
        add(jLabel35);
        jLabel35.setBounds(420, 340, 55, 14);

        jLabel36.setText("Giá:");
        add(jLabel36);
        jLabel36.setBounds(420, 380, 19, 14);
        add(txtGia);
        txtGia.setBounds(510, 380, 150, 20);

        jLabel28.setText("Tên Tour:");
        add(jLabel28);
        jLabel28.setBounds(10, 379, 47, 14);

        txtTentourve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTentourveActionPerformed(evt);
            }
        });
        add(txtTentourve);
        txtTentourve.setBounds(63, 376, 124, 20);
        add(txtTenkhve);
        txtTenkhve.setBounds(253, 376, 129, 20);

        jLabel30.setText("Tên KH:");
        add(jLabel30);
        jLabel30.setBounds(205, 379, 38, 14);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem);
        btnThem.setBounds(101, 430, 77, 32);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa);
        btnXoa.setBounds(230, 430, 77, 32);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua);
        btnSua.setBounds(360, 430, 77, 32);

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        add(btnLamMoi);
        btnLamMoi.setBounds(481, 430, 77, 32);

        jLabel2.setText("Tìm kiếm :");
        add(jLabel2);
        jLabel2.setBounds(40, 70, 50, 14);
        add(txtTimkiem);
        txtTimkiem.setBounds(100, 60, 150, 20);
    }// </editor-fold>//GEN-END:initComponents

    void showKhachHang() {
        khachhang = new KhachHangDAL().loadDataKhachHang();
        modelkh.setRowCount(0);
        for (KhachHangDTO kh : khachhang) {
            modelkh.addRow(new Object[]{
                kh.getMakh(), kh.getTenkh()
            });
        }
    }

//    void showTour() {
//        tour = new TourDAL().loadDataTour();
//        modeltour.setRowCount(0);
//        for (TourDTO t : tour) {
//            modeltour.addRow(new Object[]{
//                t.getMatour(), t.getTentour()
//            });
//        }
//    }
    void showVe() {
        ve = new VeDAL().loadDataVe();
        modelve.setRowCount(0);
        for (VeDTO v : ve) {
            modelve.addRow(new Object[]{
                v.getMave(), v.getTour().getMatour(), v.getKhachhang().getMakh(), v.getThoigiandat(), v.getTrangthai(),
                v.getGia()
            });
        }
    }

    void Reset() {
        txtTentourve.setText("");
        txtTenkhve.setText("");
        txtMave.setText("");
        txtThoigiandat.setText("");
        txtTrangthai.setText("");
        txtGia.setText("");
    }

    private void TimKiem() {
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tblVe.getModel());
        tblVe.setRowSorter(rowSorter);
        txtTimkiem.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                String text = txtTimkiem.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                String text = txtTimkiem.getText();
                if (text.length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });

    }
    private void txtTentourveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTentourveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTentourveActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        int indexKhachHang = tblKhachHang.getSelectedRow();
        if (indexKhachHang >= 0) {
            txtTenkhve.setText(modelkh.getValueAt(indexKhachHang, 1).toString());
        } else {
            JOptionPane.showMessageDialog(this, "Chọn dòng để hiển thị!!!");
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void tblTourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTourMouseClicked
        int indexTour = tblTour.getSelectedRow();
        if (indexTour >= 0) {
            txtTentourve.setText(modeltour.getValueAt(indexTour, 1).toString());
        } else {
            JOptionPane.showMessageDialog(this, "Chọn dòng để hiển thị!!!");
        }
    }//GEN-LAST:event_tblTourMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        Reset();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        int indexTour = tblTour.getSelectedRow();
        int indexKhachHang = tblKhachHang.getSelectedRow();

        String mave = txtMave.getText();
        Date thoigiandat = null;
        try {
            thoigiandat = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(txtThoigiandat.getText());
        } catch (ParseException ex) {
            Logger.getLogger(Panel_Ve.class.getName()).log(Level.SEVERE, null, ex);
        }
        String trangthai = txtTrangthai.getText();
        Float gia = Float.parseFloat(txtGia.getText());

        Boolean isOK = true;
        if (mave.length() == 0) {
            JOptionPane.showMessageDialog(this, "Mã vé không được để trống");
            isOK = false;
        } else if (trangthai.length() == 0) {
            JOptionPane.showMessageDialog(this, "Trang thái không được để trống");
            isOK = false;
        }
        if (indexTour == -1 || indexKhachHang == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để hiển thị");
            isOK = false;
        }
        if (isOK) {
            TourDTO t = tour.get(indexTour);
            KhachHangDTO kh = khachhang.get(indexKhachHang);
            VeDTO v = new VeDTO(mave, t, kh, thoigiandat, trangthai, gia);
            if (new VeBLL().addVe(v)) {
                JOptionPane.showMessageDialog(this, "Thêm thành công vé");
                ve.add(v);
                showVe();
                Reset();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm không thành công");
            }
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int indexVe = tblVe.getSelectedRow();
        String data = modelve.getValueAt(indexVe, 0).toString();
        boolean isOK = true;
        if (indexVe >= 0) {
            if (JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xoá vé không?") == 0) {
                VeDTO v = new VeDTO();
                new VeBLL().removeVe(data);
                JOptionPane.showMessageDialog(this, "Xoá thành công");
                showVe();
                Reset();
            } else {
                JOptionPane.showMessageDialog(this, "Chọn dòng để xoá");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTable tblTour;
    private javax.swing.JTable tblVe;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMave;
    private javax.swing.JTextField txtTenkhve;
    private javax.swing.JTextField txtTentourve;
    private javax.swing.JTextField txtThoigiandat;
    private javax.swing.JTextField txtTimkiem;
    private javax.swing.JTextField txtTrangthai;
    // End of variables declaration//GEN-END:variables
}
