/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import GUI.Panel_KhachHang;
//import com.sun.org.apache.xml.internal.resolver.helpers.PublicId;
import java.awt.Color;
import javax.swing.ImageIcon;


/**
 *
 * @author Win 10
 */
public class GUI_Tour extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Tour
     */
    public GUI_Tour() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = screenSize.width - 850;
        int x1 = x/2;
        this.setBounds(x1, 100, 850, 550);
        this.setResizable(false);
        this.setTitle("Quản Lý Tour Du Lịch");
        
        Image();
    }
    public void Image(){     
//        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/bg.jpg"));
        ImageIcon img = new ImageIcon("src/Images/bg.jpg");
        // KÍCH THƯỚC HÌNH ẢNH LÀ 672,496 => kích thước panel cũng vậy
        lbl_Image.setIcon(img);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
<<<<<<< Updated upstream
        btnKhHang = new javax.swing.JButton();
        btnKhSan = new javax.swing.JButton();
        btnPhTien = new javax.swing.JButton();
        btnTour = new javax.swing.JButton();
        btnVe = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 530));

        btnKhHang.setText("Khách Hàng");
        btnKhHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhHangActionPerformed(evt);
            }
        });

        btnKhSan.setText("Khách Sạn");
        btnKhSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhSanActionPerformed(evt);
            }
        });

        btnPhTien.setText("Phương Tiện");
        btnPhTien.setToolTipText("");
        btnPhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhTienActionPerformed(evt);
            }
        });

        btnTour.setText("Tour");
        btnTour.setToolTipText("");
        btnTour.addActionListener(new java.awt.event.ActionListener() {
=======
        btnCN1 = new javax.swing.JButton();
        btnCN2 = new javax.swing.JButton();
        btnCN3 = new javax.swing.JButton();
        btnCN4 = new javax.swing.JButton();
        btnCN5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ TOUR DU LỊCH");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCN1.setText("Khách Hàng");
        btnCN1.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> Stashed changes
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTourActionPerformed(evt);
            }
        });

<<<<<<< Updated upstream
        btnVe.setText("Vé");
        btnVe.addActionListener(new java.awt.event.ActionListener() {
=======
        btnCN2.setText("Khách Sạn");
        btnCN2.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> Stashed changes
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeActionPerformed(evt);
            }
        });

<<<<<<< Updated upstream
        btnTrangChu.setText("Trang chủ");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
=======
        btnCN3.setText("Phương Tiện");
        btnCN3.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> Stashed changes
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        btnCN4.setText("Tour");
        btnCN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCN4ActionPerformed(evt);
            }
        });

        btnCN5.setText("Vé");
        btnCN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCN5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
<<<<<<< Updated upstream
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKhSan, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnKhHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPhTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCN2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnCN1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCN3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCN4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCN5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> Stashed changes
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
<<<<<<< Updated upstream
                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKhHang, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKhSan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTour, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVe, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
=======
                .addComponent(btnCN1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCN2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCN3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCN4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCN5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
>>>>>>> Stashed changes
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< Updated upstream
            .addComponent(lbl_Image, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
=======
            .addGap(0, 615, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
>>>>>>> Stashed changes
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("QUẢN LÝ TOUR DU LỊCH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< Updated upstream
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
=======
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2)))
                .addContainerGap(40, Short.MAX_VALUE))
>>>>>>> Stashed changes
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
<<<<<<< Updated upstream
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
=======
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
>>>>>>> Stashed changes
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Panel_KhachHang pnKH = new Panel_KhachHang();
    Panel_KhachSan pnKS = new Panel_KhachSan();
    Panel_PhuongTien pnPT = new Panel_PhuongTien();
    Panel_Tour pnTour = new Panel_Tour();
    Panel_Ve pnVe = new Panel_Ve();
    

    private void btnKhHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhHangActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == btnKhHang){
//            jPanel3.removeAll();
//            jPanel3.remove(pnKS);
//            jPanel3.remove(pnPT);
//            jPanel3.remove(pnTour);
//            jPanel3.remove(pnVe);
//            lbl_Image.setVisible(false);
//            jPanel3.setBackground(Color.red);
//            Panel_KhachHang pn_cn1 = new Panel_KhachHang();
//            jPanel3.add(pn_cn1);
//            pnKH.setVisible(true);
//            jPanel3.add(pnKH);
             jPanel3.removeAll();
             jPanel3.add(pnKH);
             jPanel3.repaint();
             pnKH.repaint();
             pnKH.revalidate();
        }
    }//GEN-LAST:event_btnKhHangActionPerformed

    private void btnKhSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhSanActionPerformed
        // TODO add your handling code here:
        
        if(evt.getSource() == btnKhSan){
//            jPanel3.removeAll();
//            jPanel3.remove(pnKH);
//            jPanel3.remove(pnPT);
//            jPanel3.remove(pnTour);
//            jPanel3.remove(pnVe);
//            lbl_Image.setVisible(false);
//            jPanel3.setBackground(Color.yellow);
//            Panel_KhachSan pn_cn2 = new Panel_KhachSan();
//            jPanel3.add(pn_cn2);
//            pnKS.setVisible(true);
//            jPanel3.add(pnKS);
             jPanel3.removeAll();
             jPanel3.add(pnKS);
             jPanel3.repaint();
             pnKS.revalidate();
             pnKS.repaint();
        }
    }//GEN-LAST:event_btnKhSanActionPerformed

    private void btnPhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhTienActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == btnPhTien){
//            jPanel3.removeAll();
//            jPanel3.remove(pnKH);
//            jPanel3.remove(pnKS);
//            jPanel3.remove(pnTour);
//            jPanel3.remove(pnVe);
//            lbl_Image.setVisible(false);
//            jPanel3.setBackground(Color.black);
//            Panel_PhuongTien pn_cn3 = new Panel_PhuongTien();
//            jPanel3.add(pn_cn3);
//            pnPT.setVisible(true);
//            jPanel3.add(pnPT);
             jPanel3.removeAll();
             jPanel3.add(pnPT);
             jPanel3.repaint();
             pnPT.revalidate();
             pnPT.repaint();
        }
    }//GEN-LAST:event_btnPhTienActionPerformed

    private void btnTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTourActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == btnTour){
//            jPanel3.removeAll();
//            jPanel3.remove(pnKH);
//            jPanel3.remove(pnKS);
//            jPanel3.remove(pnPT);
//            jPanel3.remove(pnVe);
//            lbl_Image.setVisible(false);
//            jPanel3.setBackground(Color.black);
//            Panel_PhuongTien pn_cn3 = new Panel_PhuongTien();
//            jPanel3.add(pn_cn3);
//            pnTour.setVisible(true);
//            jPanel3.add(pnTour);
             jPanel3.removeAll();
             jPanel3.add(pnTour);
             jPanel3.repaint();
             pnTour.revalidate();
             pnTour.repaint();
        }
    }//GEN-LAST:event_btnTourActionPerformed

    private void btnVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == btnVe){
//            jPanel3.removeAll();
//            jPanel3.remove(pnKH);
//            jPanel3.remove(pnKS);
//            jPanel3.remove(pnTour);
//            jPanel3.remove(pnPT);
//            lbl_Image.setVisible(false);
//            jPanel3.setBackground(Color.black);
//            Panel_PhuongTien pn_cn3 = new Panel_PhuongTien();
//            jPanel3.add(pn_cn3);
//            pnVe.setVisible(true);
//            jPanel3.add(pnVe);
             jPanel3.removeAll();
             jPanel3.add(pnVe);
             jPanel3.repaint();
             pnVe.revalidate();
             pnVe.repaint();
        }
    }//GEN-LAST:event_btnVeActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == btnTrangChu){
//            jPanel3.removeAll();
//            jPanel3.add(lbl_Image);
//            jPanel3.repaint();
//            lbl_Image.setVisible(true);
//            jPanel3.add(lbl_Image);
             jPanel3.removeAll();
             jPanel3.add(lbl_Image);
             jPanel3.repaint();
             lbl_Image.revalidate();
             lbl_Image.repaint(); 
        }
<<<<<<< Updated upstream
    }//GEN-LAST:event_btnTrangChuActionPerformed
=======
    }//GEN-LAST:event_btnCN3ActionPerformed

    private void btnCN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCN4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCN4ActionPerformed

    private void btnCN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCN5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCN5ActionPerformed
>>>>>>> Stashed changes
 
    /**
     * @param args the command line arguments
     */
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Tour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< Updated upstream
    private javax.swing.JButton btnKhHang;
    private javax.swing.JButton btnKhSan;
    private javax.swing.JButton btnPhTien;
    private javax.swing.JButton btnTour;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnVe;
=======
    private javax.swing.JButton btnCN1;
    private javax.swing.JButton btnCN2;
    private javax.swing.JButton btnCN3;
    private javax.swing.JButton btnCN4;
    private javax.swing.JButton btnCN5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
>>>>>>> Stashed changes
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_Image;
    // End of variables declaration//GEN-END:variables
}
