/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Win 10
 */
public class Panel_PhuongTien extends javax.swing.JPanel {

    /**
     * Creates new form Panel_CN3
     */
    public Panel_PhuongTien() {
        initComponents();
        this.setSize(672,496);
        this.setBorder(BorderFactory.createLineBorder(Color.black));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhuongTien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        txtTenPT = new javax.swing.JTextField();
        txtMaPT = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(550, 480));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("PHƯƠNG TIỆN");
        add(jLabel1);
        jLabel1.setBounds(250, 20, 240, 44);

        tblPhuongTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã PT", "Tên PT", "Giá"
            }
        ));
        jScrollPane2.setViewportView(tblPhuongTien);

        add(jScrollPane2);
        jScrollPane2.setBounds(40, 70, 630, 160);

        jLabel2.setText("Mã phương tiện:");
        add(jLabel2);
        jLabel2.setBounds(100, 260, 90, 14);

        jLabel3.setText("Tên phương tiện:");
        add(jLabel3);
        jLabel3.setBounds(100, 300, 100, 14);

        jLabel4.setText("Giá:");
        add(jLabel4);
        jLabel4.setBounds(160, 340, 30, 14);

        txtGia.setForeground(new java.awt.Color(153, 153, 153));
        txtGia.setText("Giá phương tiện");
        txtGia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGiaMouseClicked(evt);
            }
        });
        add(txtGia);
        txtGia.setBounds(210, 340, 220, 20);

        txtTenPT.setForeground(new java.awt.Color(153, 153, 153));
        txtTenPT.setText("Tên phương tiện");
        txtTenPT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTenPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenPTMouseClicked(evt);
            }
        });
        add(txtTenPT);
        txtTenPT.setBounds(210, 300, 220, 20);

        txtMaPT.setForeground(new java.awt.Color(153, 153, 153));
        txtMaPT.setText("Mã phương tiện");
        txtMaPT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtMaPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaPTMouseClicked(evt);
            }
        });
        add(txtMaPT);
        txtMaPT.setBounds(210, 260, 220, 20);

        btnThem.setText("Thêm");
        add(btnThem);
        btnThem.setBounds(130, 390, 80, 40);

        btnSua.setText("Sửa");
        add(btnSua);
        btnSua.setBounds(240, 390, 80, 40);

        btnXoa.setText("Xoá");
        add(btnXoa);
        btnXoa.setBounds(350, 390, 80, 40);

        btnLamMoi.setText("Làm mới");
        add(btnLamMoi);
        btnLamMoi.setBounds(460, 300, 80, 20);

        btnTimKiem.setText("Tìm kiếm");
        add(btnTimKiem);
        btnTimKiem.setBounds(460, 260, 80, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void txtGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGiaMouseClicked
        // TODO add your handling code here:
        if(evt.getSource() == txtGia){
            txtGia.setText("");
        }
    }//GEN-LAST:event_txtGiaMouseClicked

    private void txtTenPTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenPTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenPTMouseClicked

    private void txtMaPTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaPTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPTMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPhuongTien;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaPT;
    private javax.swing.JTextField txtTenPT;
    // End of variables declaration//GEN-END:variables
}
